esphome:
  name: pec
  platform: ESP32
  board: featheresp32
  platformio_options:
      board_build.f_cpu: 240000000L

<<: !include display.yaml
<<: !include common.yaml

text_sensor:
  - platform: wifi_info
    ip_address:
      id: ipaddr
    ssid:
      id: wifissid

sensor:
  - platform: wifi_signal
    name: "RSSI"
    update_interval: 10s
    id: wifirssi

  - platform: dallas
    index: 0
    name: "Pec"
    id: "tpec"
    dallas_id: pec_hub

  - platform: dallas
    index: 0
    name: "Bojler"
    id: "tbojler"
    dallas_id: bojler_hub

  - platform: rotary_encoder
    id: rotacija
    pin_a: GPIO27
    pin_b: GPIO26
    on_clockwise:
      - lambda: |-
            if(!id(nastavi)){
              id(tft).show_next_page();
            }else{
              if (id(nastavi_pec)){
                if (id(temperatura_pec) >= 71) {
                  id(temperatura_pec) = 30;
                } else {
                  id(temperatura_pec) += 1;
                }
              }
              if (id(nastavi_bojler)){
                  if (id(temperatura_bojler) >= 71) {
                    id(temperatura_bojler) = 30;
                  } else {
                    id(temperatura_bojler) += 1;
                  }
              }
              if (id(nastavi_histereza)){
                if (id(histereza) >= 3) {
                  id(histereza) = -2.5;
                } else {
                  id(histereza) += 0.5;
                }
              }
            }
      - component.update: tft
    on_anticlockwise:
      - lambda: |-
            if(!id(nastavi)){
              id(tft).show_prev_page();
            }else{
              if (id(nastavi_pec)){
                if (id(temperatura_pec) <= 29) {
                  id(temperatura_pec) = 70;
                } else {
                  id(temperatura_pec) -= 1;
                }
              }
              if (id(nastavi_bojler)){
                  if (id(temperatura_bojler) <= 29) {
                    id(temperatura_bojler) = 70;
                  } else {
                    id(temperatura_bojler) -= 1;
                  }
              }
              if (id(nastavi_histereza)){
                  if (id(histereza) <= -3) {
                    id(histereza) = 2.5;
                  } else {
                    id(histereza) -= 0.5;
                  }
              }
            }
      - component.update: tft

binary_sensor:
  - platform: status
    id: system_status
  - platform: gpio
    pin:
      number: GPIO25
      inverted: true
    id: gumb

    on_click:
      - then:
          - lambda: |-
              if (id(on_pec)){
                id(nastavi_pec) = !id(nastavi_pec);
                id(nastavi_histereza) = false;
                id(nastavi_bojler) = false;
                id(nastavi) = !id(nastavi);
              }
              if (id(on_bojler)){
                id(nastavi_bojler) = !id(nastavi_bojler);
                id(nastavi_pec) = false;
                id(nastavi_histereza) = false;
                id(nastavi) = !id(nastavi);
              }
              if (id(on_histereza)){
                id(nastavi_histereza) = !id(nastavi_histereza);
                id(nastavi_pec) = false;
                id(nastavi_bojler) = false;
                id(nastavi) = !id(nastavi);
              }
          - component.update: tft

interval:
  - interval: 5s
    then:
      - script.execute: check_mode
  - interval: 1h
    then:
      - script.execute: clear_alerts
script:
  - id: clear_alerts
    then:
      - lambda: |-
          id(alert_sent) = false;
  - id: check_mode
    then:
      - lambda: |-
          // nevarno
          if (id(tpec).get_temp_c() >= 90){
            id(stanje) = 666;
            id(pumpa).turn_off();
            ESP_LOGI("termostat", "Prevroce");
          }else{
            // grej ce je pec dovolj topla
            if (id(tpec).get_temp_c() > id(temperatura_pec)){
              // ce je pec na splosno bolj topla od bojlerja
              if (id(tpec).get_temp_c() > id(tbojler).get_temp_c()){
                // ce je bojler hladnejsi od nastavljene temeprature
                if (id(tbojler).get_temp_c() < id(temperatura_bojler) - $HISTEREZA){
                  id(pumpa).turn_on();
                  ESP_LOGI("termostat", "Vkljucujem crpalko, bojler hladnejsi od peci");
                }
                if (id(tbojler).get_temp_c() > id(temperatura_bojler) + $HISTEREZA){
                  id(stanje) = 3;
                  id(pumpa).turn_off();
                  ESP_LOGI("termostat", "Izklucujem crpalko, temperatura dosezena");
                }
              }else{
                id(stanje) = 2;
                id(pumpa).turn_off();
                ESP_LOGI("termostat", "Izklucujem crpalko, pec hladnejsa od bojlerja");
              }
            }else{
              id(stanje) = 1;
              id(pumpa).turn_off();
              ESP_LOGI("termostat", "Izklucujem crpalko, pec hladnejsa od nastavitve");
            }
          }
